Listen = "0.0.0.0:5678"
ProxyURL = "http://127.0.0.1:7890"
EnableAuth = false
Tokens = [""]

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80"
  Name = "CHAT_SESSION_ID"
  Path = "/"
  Domain = ""
  MaxAge = 86400
  Secure = true
  HttpOnly = false
  SameSite = 4

[Chat]
  ApiURL = "https://api.openai.com/v1/chat/completions"
  ApiKeys = ["xxx"]
  Model = "gpt-3.5-turbo"
  Temperature = 1.0
  MaxTokens = 1024
  EnableContext = true
